[package]
name = "provider-profile"
version.workspace = true
edition.workspace = true

[dependencies]
borsh.workspace = true
fs-err = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
