[toolchain]
channel = "nightly-2025-11-27"
targets = [
    "x86_64-unknown-linux-gnu",
    "wasm32-unknown-unknown",
    "aarch64-apple-darwin",
]
components = ["rust-analyzer", "rustfmt", "clippy"]
#profile = "minimal"
