[package]
name = "np-offering"
version.workspace = true
edition.workspace = true

[dependencies]
fs-err = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
np-json-search = { path = "../np-json-search" }
strsim.workspace = true
