[package]
name = "decent-cloud-api"
version.workspace = true
edition = "2021"

[[bin]]
name = "api-server"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
base64.workspace = true
borsh.workspace = true
candid.workspace = true
clap.workspace = true
dcc-common = { path = "../common" }
dotenv.workspace = true
ic-agent.workspace = true
ledger-map = { path = "../ledger-map" }
poem.workspace = true
provider-offering = { path = "../provider-offering" }
provider-profile = { path = "../provider-profile" }
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
sqlx.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
